"""empty message

Revision ID: e4dde2baf6f6
Revises: cb7aa42d36f1
Create Date: 2017-04-27 19:43:20.790817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4dde2baf6f6'
down_revision = 'cb7aa42d36f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('year_released', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'song', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'song', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_table('album')
    # ### end Alembic commands ###
